export const elements = {
    userName: '#user-name',
    password: '#password',
    userOne: 'standard_user',
    userTwo: 'locked_out_user',
    userThree: 'problem_user',
    userFour: 'performance_glitch_user',
    passwordForAllUsers: 'secret_sauce',
    clickLogin: '#login-button',
    selectOptions: '.bm-burger-button',
    logout: '#logout_sidebar_link',
    validarMensagemDeErro: "[data-test='error']",
    adiconarProdutosNoCarrinho: '.btn_inventory',
    clicarCarrinho: '.fa-shopping-cart',
    removerProdutosDoCarrinho: '.cart_button',
    validarTituloItemUm: '.inventory_details_name',
    validarTituloItemDois: '.inventory_details_name',
    validarTituloItemTres: '.inventory_details_name',
    validarTituloItemQuatro: '.inventory_details_name',
    validarTituloItemCinco: '.inventory_details_name',
    validarTituloItemUmSeis: '.inventory_details_name',
}