export const elements = {
    userName: '#user-name',
    password: '#password',
    userOne: 'standard_user',
    userTwo: 'locked_out_user',
    userThree: 'problem_user',
    userFour: 'performance_glitch_user',
    passwordForAllUsers: 'secret_sauce',
    clickLogin: '#login-button',
    selectOptions: '.bm-burger-button',
    logout: '#logout_sidebar_link',
    validarMensagemDeErro: "[data-test='error']",
    adiconarProdutosNoCarrinho: '.btn_inventory',
    clicarCarrinho: '.fa-shopping-cart',
    removerProdutosDoCarrinho: '.cart_button',
    validarTituloItemUm: '.inventory_item_name',
    validarTituloItemDois: '.inventory_item_name',
    validarTituloItemTres: '.inventory_item_name',
    validarTituloItemQuatro: '.inventory_item_name',
    validarTituloItemCinco: '.inventory_item_name',
    validarTituloItemSeis: '.inventory_item_name',
    btnCheckout: '.btn_action',
    firstNameElement: '#first-name',
    firstName: 'Pedro',
    lastNameElement: '#last-name',
    lastName: 'Campos',
    postalCodeElement: '#postal-code',
    postalCode: '72603-316',
    btnContinue: '.btn_primary',
    btnFinish: '.btn_action',
    valorDosItens: '.summary_subtotal_label',
    valorDaTaxa: '.summary_tax_label',
    valorTotal: '.summary_total_label',
    validarConfimarcaoDoPedido: '.complete-header',
    validarSubTituloDaConirmacaoDoPedido: '.complete-text'
    
}